### ISSUE TITLE
[BUG]: it's "ffmpeg" NOT "ffmpeg-python" !!!

### ISSUE THREAD

**Issue by illtellyoulater** [CiaraStrawberry/TemporalKit#110]
In install.py you have:

```
if not launch.is_installed("ffmpeg-python"):
    launch.run_pip("install ffmpeg-python", "Install \"ffmpeg-python\" requirements for TemporalKit extension")

```

but this is causing "ffmpeg-python" to be always reinstalled.

The correct name to use for the check is 

`if not launch.is_installed("ffmpeg")`

Please fix it asap as this is causing environments to break, inconsistencies and so many headaches.

**Comment by CiaraStrawberry** [comment]
should be fixed now, please give a shout if that causes any further issues for you after the update.

**Comment by illtellyoulater** [comment]
@CiaraStrawberry cool, but perhaphs I rushed a bit too much opening issues all around, as probably it makes much more sense to fix this on the sd-webui side: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13487

Anyway, while it's not fixed there , with your commit I got your extension to properly load dependancies (instead of continuously being reinstalled for no reason at every launch).
